[xray_log]
# см https://xtls.github.io/en/config/log.html
loglevel = "none"
access = "/dev/null"
error = "/dev/null"
dns_log = false
mask_address = ""

[settings]
urls = [
	"https://www.gstatic.com/generate_204",
	"https://cloudflare.com/cdn-cgi/trace"
]
speedtest_url = ""

# дефолт "Happ/3.26.3"
user_agent = ""
# на случай если нужен статический hwid, дефолт рандом
hwid = ""

# при allow = true, разрешено только указанное в list

[settings.protocols]
allow = false
list = ["bless+over+pppoe"]

[settings.countries]
allow = false
list = ["KP"]

[settings.cidrs]
allow = true
list = ["0.0.0.0/0", "::/0"]
